services:
  nginx:
    image: nginx:latest
    volumes:
      - ./config/proxy.conf:/etc/nginx/conf.d/default.conf
    restart: 'unless-stopped'
    ports:
      - '80:80'
    depends_on:
      - motioneye
      - mkdocs

  motioneye:
    image: ccrisan/motioneye:dev-amd64
    container_name: motioneye
    environment:
      TIMEZONE: "Australia/Perth"
      PUID: "0"
      PGID: "0"
    volumes:
      - ./motioneye/config:/config #Config Storage
      - ./motioneye/storage:/home/nobody/media  #File Storage
    devices:
     - /dev/video0
     - /dev/video2
    ports:
      - 8081:8081
      - 8765:8765
    restart: always

  mkdocs:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs
    ports:
      - 8000:8000
    volumes:
      - ./docs:/docs